// ============================================================
// Pepper Spicy Restaurant — Menu Data
// Rebuilt to match Final_Menu-1.pdf exactly.
// Edit this file to update prices, items, categories, contact.
// ASP = As per market price.
// ============================================================

const restaurant = {
  name: "Pepper Spicy Restaurant",
  nameArabic: "مطعم بيبر سبيسي",
  sloganArabic: "تعال جائعاً",
  tagline: "A fiery taste of Kerala in the heart of Al Ain",
  address: "Opp. Bin Fadel Readymix, Sanaiya — Al Ain, UAE",
  phones: ["055 884 1776", "052 609 0360"],
  hours: "Open daily · 6:00 AM – 1:00 AM",
  delivery: "Home Delivery Available",
  currency: "AED",
};

const categories = [
  { id: "breakfast", title: "Breakfast", tagline: "A good breakfast is the start of a good day", items: [
    { name: "Idly Set", price: "6" },
    { name: "Poori Bhaji", price: "7" },
    { name: "Plain Dosa", price: "6" },
    { name: "Set Dosa", price: "6" },
    { name: "Ghee Roast", price: "7" },
    { name: "Onion Uthappam", price: "7" },
    { name: "Egg Dosa (S/D)", price: "6 / 9" },
    { name: "Masala Dosa", price: "7" },
    { name: "Puttu Kadala", price: "7" },
    { name: "Upma", price: "5" },
    { name: "Omlette", price: "3 / 4" },
  ]},
  { id: "english-breakfast", title: "English Breakfast", items: [
    { name: "Toasted Cheese + Juice", price: "12" },
    { name: "Butter Toast + Juice", price: "12" },
    { name: "Bread & Jam + Juice", price: "12" },
    { name: "Half Fry w/ Bread + Juice", price: "12" },
    { name: "Boiled Egg Sandwich + Juice", price: "12" },
    { name: "Corn Flakes", price: "12" },
    { name: "Oats", price: "12" },
    { name: "Maggi Noodles", price: "12" },
  ]},
  { id: "breakfast-curry", title: "Breakfast Curry", items: [
    { name: "Tomato Curry", price: "5" },
    { name: "Mix Veg Curry", price: "6" },
    { name: "Bhaji", price: "4" },
    { name: "Green Peas Curry", price: "6 / 10" },
    { name: "Mathi Mulakittathu", price: "ASP" },
    { name: "Ayala Mulakittathu", price: "ASP" },
    { name: "Cherupayar Curry", price: "5" },
    { name: "Kadala Curry", price: "5" },
    { name: "Egg Curry", price: "4 / 6" },
    { name: "Egg Roast", price: "5 / 7" },
    { name: "Beef Curry", price: "8 / 12" },
    { name: "Chicken Curry", price: "7 / 11" },
  ]},
  { id: "rotti", title: "Rotti Items", items: [
    { name: "Kallappam", price: "1" },
    { name: "Neypathal", price: "2" },
    { name: "Wheat Puttu (1 pc)", price: "2" },
    { name: "Rice Puttu", price: "1.50" },
    { name: "Puttu Kutti", price: "3" },
    { name: "Kerala Porotta", price: "1" },
    { name: "Wheat Porotta", price: "1.50" },
    { name: "Nool Porotta", price: "3" },
    { name: "Alu Porotta", price: "3" },
    { name: "Mix Porotta", price: "3" },
    { name: "Paneer Porotta", price: "3" },
    { name: "Gobi Porotta", price: "3" },
    { name: "Coin Porotta", price: "1" },
    { name: "Chappathi", price: "1" },
    { name: "Vellayappam", price: "1" },
    { name: "Nice Pathiri", price: "1" },
    { name: "Pathal", price: "1" },
    { name: "Idiyappam", price: "1" },
  ]},
  { id: "soups", title: "Soup Specials", items: [
    { name: "Manchow Soup (Veg / Chi)", price: "8 / 10" },
    { name: "Noodles Soup (Veg / Chi)", price: "8 / 10" },
    { name: "Clear Soup (Veg / Chi)", price: "8 / 10" },
    { name: "Cream of Tomato Soup", price: "10" },
    { name: "Cream of Chicken", price: "10" },
    { name: "Cream of Mushroom", price: "10" },
    { name: "Hot & Sour (Veg / Chi)", price: "8 / 12" },
    { name: "Sweet Corn Soup (Veg / Chi)", price: "8 / 10" },
    { name: "Chicken Soup", price: "10" },
    { name: "Mutton Soup", price: "12" },
    { name: "Veg Soup", price: "8" },
    { name: "Cream of Seafood", price: "14" },
    { name: "Nadan Soup", price: "12" },
  ]},
  { id: "starters", title: "Starters", tagline: "Delicious and fresh", items: [
    { name: "Chicken Lollipop", price: "16" },
    { name: "Chicken Pepper Dry Fry", price: "16" },
    { name: "Chicken 65 (8 pc)", price: "16" },
    { name: "Dragon Chicken", price: "19" },
    { name: "Crispy Fried Chicken", price: "18" },
    { name: "Crumb Fried Chicken", price: "20" },
    { name: "Chicken Chilli (IND)", price: "17" },
    { name: "Drum of Heaven Chicken", price: "19" },
    { name: "Beef Pepper Dry Fry", price: "18" },
    { name: "Beef Dry Fry", price: "18" },
    { name: "Beef Chilli (IND)", price: "19" },
    { name: "Meat Boll (Chik / Beef)", price: "20 / 22" },
    { name: "Prawns Chilli Dry", price: "21" },
    { name: "Dynamite Shrimps", price: "21" },
    { name: "Gobi 65", price: "16" },
    { name: "Paneer 65", price: "16" },
    { name: "French Fries", price: "8 / 12" },
    { name: "Mushroom Dry Fry", price: "15" },
    { name: "Onion Ring", price: "15" },
  ]},
  { id: "meals", title: "Meals", items: [
    { name: "Pothi Choru", price: "15" },
    { name: "Motta Set", price: "9" },
    { name: "Barik Set", price: "9" },
    { name: "Motta Set Parcel", price: "10" },
    { name: "Barik Set Parcel", price: "10" },
  ]},
  { id: "rice-items", title: "Rice Items", items: [
    { name: "Plain Rice", price: "5" },
    { name: "Biriyani Rice", price: "6" },
    { name: "Lemon Rice", price: "10" },
    { name: "Tamarind Rice", price: "10" },
    { name: "Tomato Rice", price: "10" },
    { name: "Curd Rice", price: "10" },
  ]},
  { id: "pulao", title: "Pulao Items", items: [
    { name: "Veg Pulao", price: "10" },
    { name: "Chicken Pulao", price: "13" },
    { name: "Mutton Pulao", price: "15" },
  ]},
  { id: "biriyani", title: "Biriyani Corner", tagline: "Slow-cooked, layered, legendary", items: [
    { name: "Malabar Dum Biriyani", price: "13" },
    { name: "Thalassery Dum Biriyani", price: "14" },
    { name: "Hydrabadi Biriyani", price: "15" },
    { name: "Prawns Roasted Biriyani", price: "ASP" },
    { name: "Mutton Roasted Dum Biriyani", price: "18" },
    { name: "Beef Roasted Dum Biriyani", price: "17" },
    { name: "Veg Roasted Biriyani", price: "12" },
    { name: "Egg Roasted Biriyani", price: "13" },
    { name: "Kizhi Biriyani (C / B / M)", price: "16 / 18 / 20" },
    { name: "Fish Biriyani", price: "ASP" },
    { name: "Chicken Fry Biriyani", price: "14" },
    { name: "Chicken Legon Biriyani (Sun)", price: "17" },
    { name: "Chicken Mandi (Saturday)", price: "14 / 25 / 40" },
  ]},
  { id: "bucket", title: "Bucket Biriyani", tagline: "Feast for the family", items: [
    { name: "Chicken 65 Biriyani (2 Persons)", price: "25" },
    { name: "Chicken 65 Biriyani (3–4 Persons)", price: "45" },
    { name: "Chicken 65 Biriyani (5–6 Persons)", price: "65" },
    { name: "Chicken Mughlai Biriyani (2 Persons)", price: "25" },
    { name: "Chicken Mughlai Biriyani (3–4 Persons)", price: "45" },
    { name: "Chicken Mughlai Biriyani (5–6 Persons)", price: "65" },
    { name: "Chicken Fry Biriyani (4 Pcs)", price: "25" },
    { name: "Chicken Fry Biriyani (8 Pcs)", price: "45" },
    { name: "Chicken Fry Biriyani (12 Pcs)", price: "65" },
  ]},
  { id: "ghee-combo", title: "Ghee Rice Combo", items: [
    { name: "Ghee Rice & Beef Palli Curry", price: "13" },
    { name: "Ghee Rice & Beef Roast", price: "14" },
    { name: "Ghee Rice & Beef Varatharachath", price: "16" },
    { name: "Ghee Rice & Beef Pepper Masala", price: "18" },
    { name: "Ghee Rice & Chicken Palli Curry", price: "13" },
    { name: "Ghee Rice & Chicken Roast", price: "14" },
    { name: "Ghee Rice & Chicken Pepper Masala", price: "17" },
    { name: "Ghee Rice & Chicken Varatharachath", price: "15" },
  ]},
  { id: "fried-rice", title: "Fried Rice", items: [
    { name: "Chicken Fried Rice", price: "15" },
    { name: "Beef Fried Rice", price: "16" },
    { name: "Prawns Fried Rice", price: "19" },
    { name: "Egg Fried Rice", price: "12" },
    { name: "Veg. Fried Rice", price: "10" },
    { name: "Mushroom Fried Rice", price: "14" },
    { name: "Mixed Fried Rice", price: "19" },
    { name: "Triple Fried Rice", price: "20" },
    { name: "American Chopsuey", price: "25" },
  ]},
  { id: "schezwan-fried-rice", title: "Schezwan Fried Rice", items: [
    { name: "Chi. Fried Rice", price: "15" },
    { name: "Beef Fried Rice", price: "16" },
    { name: "Egg Fried Rice", price: "12" },
    { name: "Prawns Fried Rice", price: "18" },
    { name: "Mix. Fried Rice", price: "18" },
    { name: "Veg. Fried Rice", price: "10" },
  ]},
  { id: "noodles", title: "Noodles", items: [
    { name: "Chicken Noodles", price: "14" },
    { name: "Beef Noodles", price: "16" },
    { name: "Prawns Noodles", price: "19" },
    { name: "Egg Noodles", price: "13" },
    { name: "Veg. Noodles", price: "12" },
    { name: "Mix Noodles", price: "20" },
    { name: "Chinese Chopusey", price: "25" },
  ]},
  { id: "schezwan-noodles", title: "Schezwan Noodles", items: [
    { name: "Chicken Noodles", price: "16" },
    { name: "Beef Noodles", price: "17" },
    { name: "Prawns Noodles", price: "20" },
    { name: "Egg Noodles", price: "14" },
    { name: "Veg. Noodles", price: "12" },
    { name: "Mix Noodles", price: "18" },
  ]},
  { id: "special", title: "Pepper Spicy Special", tagline: "Chef's signatures", items: [
    { name: "Pothinkaal", price: "ASP" },
    { name: "Kizhi Porotta (Chi / Beef)", price: "16 / 18" },
    { name: "Nidhi Porotta", price: "20" },
    { name: "Paal Porotta", price: "17" },
    { name: "Tandoori Chicken Combo", price: "15" },
    { name: "Chicken Kadai", price: "18" },
    { name: "Chicken Chettinad", price: "22" },
    { name: "Payyoli Chicken Fry", price: "23" },
    { name: "Malabar Chicken Curry", price: "16" },
    { name: "Pakshikood Chicken", price: "40" },
    { name: "Sundari Kozhi", price: "42" },
    { name: "Sundari Kozhi & 10 Porotta Combo", price: "50" },
    { name: "Chicken Kondattom", price: "20" },
    { name: "Chicken Varaval", price: "17" },
    { name: "Chicken Pottitherichath", price: "18" },
    { name: "Travancore Chicken", price: "28" },
    { name: "Mutton Pepper Fry", price: "28" },
    { name: "Kuttanadan Duck Roast", price: "28" },
    { name: "Kappa Biriyani (Chi / Beef)", price: "16 / 17" },
    { name: "Chicken Chukka", price: "15" },
    { name: "Mutton Tala Curry", price: "17" },
    { name: "Kada Masala / Fry", price: "22 / 27" },
    { name: "Chicken Nirachath", price: "38" },
    { name: "Beef Kanthari (Idichath)", price: "24" },
    { name: "Bellari Beef Fry", price: "18" },
    { name: "Chicken Varatharachath", price: "19" },
    { name: "Urulikoot Chicken", price: "20" },
    { name: "Kothu Porotta (Chi / Beef)", price: "15 / 16" },
    { name: "Elaneer Chicken", price: "35" },
    { name: "Paal Kappa", price: "10" },
    { name: "Paal Kappa Beef Combo", price: "20" },
    { name: "Kappa", price: "6" },
    { name: "Kapp Beef Combo", price: "14" },
    { name: "Kappa Fish Curry (Mathi / Ayala)", price: "13" },
    { name: "Kadal Koot", price: "ASP" },
  ]},
  { id: "beef", title: "Beef Special", items: [
    { name: "Beef Fry", price: "13" },
    { name: "Beef Coconut Fry", price: "16" },
    { name: "Beef Ularth", price: "17" },
    { name: "Beef Roast", price: "17" },
    { name: "Beef Mulakittath", price: "21" },
    { name: "Beef Varatharachath", price: "19" },
    { name: "Beef Pottitherichath", price: "21" },
    { name: "Beef Kondattom", price: "21" },
    { name: "Beef Pepper Masala", price: "21" },
    { name: "Beef Kantharikoot", price: "22" },
    { name: "Beef Komban Kizhi", price: "21" },
    { name: "Beef Kuruma", price: "19" },
    { name: "Beef Varattu", price: "18" },
    { name: "Beef Chukka", price: "17" },
    { name: "Beef Chaps", price: "17" },
  ]},
  { id: "mutton", title: "Mutton Special", items: [
    { name: "Mutton Kadai", price: "19" },
    { name: "Mutton Masala", price: "21" },
    { name: "Mutton Curry", price: "17" },
    { name: "Mutton Pepper Masala", price: "20" },
    { name: "Mutton Rogan Josh", price: "21" },
    { name: "Mutton Roast", price: "19" },
    { name: "Mutton Coconut Fry", price: "21" },
    { name: "Mutton Hydrabadi Curry", price: "21" },
    { name: "Mutton Kuruma", price: "21" },
    { name: "Mutton Varattu Masala", price: "20" },
    { name: "Mutton Green Pepper Masala", price: "22" },
  ]},
  { id: "chicken", title: "Chicken Special", items: [
    { name: "Naadan Chicken Curry", price: "8 / 12" },
    { name: "Chicken Masala", price: "15" },
    { name: "Chicken Pepper Masala", price: "16" },
    { name: "Chicken Varatharachath", price: "18" },
    { name: "Chicken Peralan", price: "16" },
    { name: "Chicken Varattiyath", price: "16" },
    { name: "Chicken Roast", price: "17" },
    { name: "Chicken Tawa", price: "16" },
    { name: "Chicken Muglai", price: "17" },
    { name: "Chicken Chettinad", price: "21" },
    { name: "Chicken Fry Special (5 pc)", price: "20" },
    { name: "Chicken Fry (3 pc)", price: "14" },
    { name: "Chicken Stew", price: "17" },
    { name: "Chicken Kuruma", price: "19" },
    { name: "Chicken Mulakittath", price: "13" },
    { name: "Chicken Kantharikoot", price: "22" },
    { name: "Chicken Tikka Masala", price: "18" },
    { name: "Kadai Chicken", price: "16" },
    { name: "Butter Chicken", price: "21" },
    { name: "Handi Chicken", price: "14" },
    { name: "Rara Chicken", price: "14" },
    { name: "Palak Chicken", price: "13" },
    { name: "Chicken Do-Payaza", price: "14" },
    { name: "Chicken Kolapoori", price: "14" },
    { name: "Chicken Angara", price: "14" },
    { name: "Cream Chicken", price: "14" },
    { name: "Kali Mirchi Chicken", price: "14" },
    { name: "Chicken Takatak", price: "15" },
    { name: "Methi Malai Chicken", price: "13" },
    { name: "Chicken Chaps", price: "13" },
    { name: "Chicken Drumstick Fry (2 / 3 pc)", price: "7 / 10" },
  ]},
  { id: "chatti", title: "Chatti Special", items: [
    { name: "Chicken Chatti Curry", price: "20 / 35" },
    { name: "Mutton Chatti Curry", price: "25 / 45" },
    { name: "Beef Chatti Curry", price: "24 / 40" },
    { name: "Fish Chatti Curry", price: "ASP" },
    { name: "Fish Mango Chatti Curry", price: "ASP" },
    { name: "Prawns Chatti Curry", price: "ASP" },
    { name: "Malabar Chicken Chatti Curry", price: "22 / 38" },
    { name: "Angamaly Fish Mango Curry", price: "ASP" },
    { name: "Ayala Mango Curry", price: "ASP" },
    { name: "King Fish Mango Curry", price: "ASP" },
    { name: "Fish Mango Curry", price: "ASP" },
    { name: "Fish Shap Curry", price: "ASP" },
    { name: "Beef Shap Curry", price: "20" },
    { name: "Fish Nirvana", price: "ASP" },
    { name: "Fish Moli", price: "ASP" },
    { name: "Fish Chettinad", price: "ASP" },
  ]},
  { id: "fish-special", title: "Fish Special", items: [
    { name: "King Fish Roast", price: "ASP" },
    { name: "King Fish Fry", price: "ASP" },
    { name: "King Fish Masala", price: "ASP" },
    { name: "Mathi Varattiyath", price: "ASP" },
    { name: "Mathi Kurumulakittath", price: "ASP" },
    { name: "Fish Thala Curry", price: "ASP" },
    { name: "Fish Mulakittath", price: "ASP" },
    { name: "Kuttanadan Fish Curry", price: "ASP" },
    { name: "Fish Mappas", price: "ASP" },
    { name: "Hammour Pollichath", price: "ASP" },
    { name: "Avoli Pollichath", price: "ASP" },
    { name: "Sherry Pollichath", price: "ASP" },
    { name: "Sea Bream Pollichath", price: "ASP" },
    { name: "King Fish Pollichath", price: "ASP" },
    { name: "Karimeen Pollichath", price: "ASP" },
    { name: "Hammour Grilled", price: "ASP" },
    { name: "Avoli Grilled", price: "ASP" },
    { name: "Sherry Grilled", price: "ASP" },
    { name: "Sea Bream Grilled", price: "ASP" },
    { name: "Kanthari Fish Tawa Fry", price: "ASP" },
    { name: "Cheriyulli Fish Tawa", price: "ASP" },
    { name: "Fish Tawa", price: "ASP" },
    { name: "Hammour Fillet Tawa", price: "ASP" },
  ]},
  { id: "seafood", title: "Seafood Specials", items: [
    { name: "Prawns Tawa Fry", price: "ASP" },
    { name: "Seafood Bucket", price: "ASP" },
    { name: "Crab Roast", price: "ASP" },
    { name: "Crab Fry", price: "ASP" },
    { name: "Crab Masala", price: "ASP" },
    { name: "Prawns Roast", price: "ASP" },
    { name: "Prawns Fry", price: "ASP" },
    { name: "Prawns Masla", price: "ASP" },
    { name: "Prawns Paal Kizhi", price: "ASP" },
    { name: "Squid Roast", price: "ASP" },
    { name: "Squid Masla", price: "ASP" },
    { name: "Squid Fry", price: "ASP" },
  ]},
  { id: "vegetable", title: "Vegetable Specials", items: [
    { name: "Aloo Gobi", price: "10" },
    { name: "Aloo Masala", price: "10" },
    { name: "Aloo Palak", price: "10" },
    { name: "Aloo Mutter", price: "9" },
    { name: "Dal Fry", price: "8" },
    { name: "Dal Palak", price: "10" },
    { name: "Dal Makhani", price: "12" },
    { name: "Palak Paneer", price: "12" },
    { name: "Dal Tadka", price: "10" },
    { name: "Veg. Masala", price: "10" },
    { name: "Veg. Kolapuri", price: "10" },
    { name: "Veg Do Payaza", price: "10" },
    { name: "Mushroom Masala", price: "12" },
    { name: "Mushroom Kadai", price: "12" },
    { name: "Mushroom Chilli", price: "13" },
    { name: "Paneer Butter Masala", price: "14" },
    { name: "Paneer Mutter Masala", price: "13" },
    { name: "Paneer Kadai", price: "14" },
    { name: "Sahi Paneer", price: "12" },
    { name: "Gobi Masala / Chilli / 65", price: "11" },
    { name: "Chana Masala", price: "10" },
    { name: "Green Peas Masala", price: "8" },
    { name: "Veg. Kadai", price: "11" },
    { name: "Navaratna Kuruma", price: "12" },
    { name: "Veg. Kuruma", price: "10" },
    { name: "Veg. Stew", price: "12" },
    { name: "Bindi Masala", price: "10" },
    { name: "Bindi Fry", price: "9" },
    { name: "Soya Fry / Roast", price: "10" },
    { name: "Corn Palak", price: "12" },
  ]},
  { id: "chinese", title: "Chinese Cuisine", items: [
    { name: "Garlic Chicken", price: "17 / 15" },
    { name: "Chicken Manchurian", price: "17" },
    { name: "Schezwan Chi (Dry / Gravy)", price: "18 / 20" },
    { name: "Chilli Chicken", price: "16 / 17" },
    { name: "Lemon Chicken Dry", price: "16" },
    { name: "Ginger Chicken (Dry / Gravy)", price: "16 / 17" },
    { name: "Honey Glazed Chicken", price: "20" },
    { name: "Beef Manchurian", price: "18" },
    { name: "Chilli Beef (Dry / Gravy)", price: "16 / 18" },
    { name: "Ginger Beef (Dry / Gravy)", price: "16 / 18" },
    { name: "Garlic Beef (Dry / Gravy)", price: "16 / 18" },
    { name: "Prawns Manchurian", price: "22" },
    { name: "Prawns Chilli (Dry / Gravy)", price: "22 / 24" },
    { name: "Garlic Prawns (Dry / Gravy)", price: "19 / 21" },
    { name: "Ginger Prawns", price: "19 / 21" },
    { name: "Schezwan Prawns", price: "19 / 21" },
    { name: "Paneer Chilli (Dry / Gravy)", price: "16 / 18" },
    { name: "Chilli Gobi (Dry / Gravy)", price: "15 / 14" },
    { name: "Paneer Manchurian", price: "15 / 17" },
    { name: "Gobi Manchurian", price: "14 / 15" },
    { name: "Garlic Fish (Dry / Gravy)", price: "ASP" },
    { name: "Chilli Fish (Dry / Gravy)", price: "ASP" },
    { name: "Ginger Fish", price: "ASP" },
  ]},
  { id: "grill", title: "Grill Corner", items: [
    { name: "Chicken Charcoal Normal", price: "22 / 38" },
    { name: "Peri Peri Chicken Charcoal", price: "26 / 43" },
    { name: "Green Chilli Charcoal", price: "26 / 43" },
    { name: "Pepper Chicken Charcoal", price: "26 / 43" },
    { name: "Red Chilli Charcoal", price: "26 / 43" },
    { name: "Honey Chicken Charcoal", price: "26 / 43" },
    { name: "Mix Grill", price: "55 / 95" },
    { name: "Grilled Chicken", price: "20 / 28" },
    { name: "Chicken Kabab", price: "17" },
    { name: "Mutton Kabab", price: "24" },
    { name: "Chicken Tikka", price: "16" },
    { name: "Mutton Tikka", price: "22" },
    { name: "Chicken Wings", price: "15" },
    { name: "Charcoal Pollichath", price: "26 / 48" },
    { name: "Dynamite Charcoal", price: "28 / 48" },
    { name: "Grilled Dynamite", price: "28 / 48" },
  ]},
  { id: "weekend-special", title: "Weekend Special", items: [
    { name: "Deer Roast / Masala", price: "ASP" },
    { name: "Rabit Roast / Masala", price: "ASP" },
    { name: "Duck Roast / Masala", price: "ASP" },
    { name: "Kada Roast / Masala", price: "ASP" },
    { name: "Camel Roast / Masala", price: "ASP" },
    { name: "Elaneer Chicken", price: "ASP" },
    { name: "Duck Pollichath", price: "ASP" },
    { name: "Dil Kush Chicken", price: "ASP" },
  ]},
  { id: "porotta-sandwiches", title: "Porotta Sandwiches", items: [
    { name: "Egg Sandwich (S/D)", price: "3 / 4" },
    { name: "Chicken Sandwich", price: "4" },
    { name: "Chicken Chilli Sandwich", price: "5" },
    { name: "Beef Sandwich", price: "5" },
    { name: "Tikka Sandwich", price: "10" },
    { name: "Zinger Porotta", price: "12" },
    { name: "Hotdog Sandwich", price: "7" },
  ]},
  { id: "wrap-sandwiches", title: "Wrap Sandwiches", items: [
    { name: "Sheesh Tawook", price: "14" },
    { name: "Tikka Wrap", price: "13" },
    { name: "Hotdog Wrap", price: "12" },
    { name: "Arabic Wrap", price: "15" },
    { name: "Prawns Wrap", price: "13" },
    { name: "Chicken 65 Wrap", price: "12" },
    { name: "Zinger Wrap", price: "13" },
    { name: "Nuggets Wrap", price: "12" },
    { name: "Chicken Lemon Wrap", price: "12" },
    { name: "Beef Wrap", price: "12" },
    { name: "Egg Wrap", price: "8" },
    { name: "Veg. Wrap", price: "10" },
  ]},
  { id: "juice", title: "Juice, Sarbath & Mojito Corner", items: [
    { name: "Lemon", price: "5" },
    { name: "Lemon Soda", price: "6" },
    { name: "Lemon Mint (Spicy, Normal)", price: "6" },
    { name: "Mango Juice", price: "10" },
    { name: "Avacado", price: "10" },
    { name: "Apple Juice", price: "10" },
    { name: "Sweet Melon", price: "10" },
    { name: "Water Melon", price: "8" },
    { name: "Orange", price: "10" },
    { name: "Carrot", price: "10" },
    { name: "ABC", price: "10" },
    { name: "Tender Coconut", price: "10" },
    { name: "Lee Blue Mojito", price: "10" },
    { name: "Water Melon Mojito", price: "10" },
    { name: "Passion Fruit Mojito", price: "10" },
    { name: "Blueberry Mojito", price: "10" },
    { name: "Strawberry Mojito", price: "10" },
    { name: "Mango Mojito", price: "10" },
    { name: "Kiwi Mojito", price: "10" },
    { name: "Pomegranate Mojito", price: "10" },
    { name: "Nannari Sarbath", price: "8" },
    { name: "Nellikka Kanthari Sarbath", price: "8" },
    { name: "Soda Sarbath", price: "7" },
    { name: "Fresh Juice 250 / 500 / 1Ltr", price: "10 / 18 / 28" },
  ]},
  { id: "shakes", title: "Shake Corner", items: [
    { name: "Chocolate Shake", price: "13" },
    { name: "Strawberry Shake", price: "13" },
    { name: "Pistachio Shake", price: "13" },
    { name: "Vanilla Shake", price: "13" },
    { name: "Mango Shake", price: "13" },
    { name: "Avacado Shake", price: "13" },
    { name: "Sharjah Shake", price: "13" },
    { name: "Chikko Shake", price: "13" },
  ]},
  { id: "crush-milk", title: "Crush Milk", items: [
    { name: "Lotus Crush Milk", price: "14" },
    { name: "Kitkat Crush Milk", price: "14" },
    { name: "Nutella Crush Milk", price: "14" },
    { name: "Snickers Crush Milk", price: "14" },
    { name: "Galaxy Crush Milk", price: "14" },
    { name: "Oreo Crush Milk", price: "14" },
    { name: "Chocolate Dates", price: "15" },
  ]},
  { id: "smoothies", title: "Smoothies", items: [
    { name: "Mango Smoothie", price: "12" },
    { name: "Strawberry Smoothie", price: "12" },
    { name: "Passion Fruit Smoothie", price: "12" },
    { name: "Avacado Smoothie", price: "12" },
  ]},
  { id: "tea", title: "Tea & Coffee", items: [
    { name: "Karak Tea", price: "1.50" },
    { name: "Fresh Milk Tea", price: "1.50" },
    { name: "Samavar Tea", price: "1.50" },
    { name: "Black Tea", price: "1.50" },
    { name: "Lemon Tea", price: "1.50" },
    { name: "Ginger Tea", price: "1.50" },
    { name: "Green Tea", price: "1.50" },
    { name: "Nescafe", price: "3" },
    { name: "Horlicks", price: "4" },
    { name: "Boost", price: "4" },
    { name: "Plain Milk", price: "3" },
    { name: "Badam Milk", price: "4" },
    { name: "Safron Fresh Milk Tea", price: "4" },
    { name: "Safron Karak Tea", price: "3" },
    { name: "Butter Milk", price: "4" },
    { name: "Fresh Milk Coffee", price: "3" },
    { name: "Black Coffee", price: "2" },
  ]},
  { id: "desserts", title: "Desserts Corner", items: [
    { name: "Mixed Ice Cream", price: "8" },
    { name: "Fruit Salad with Ice Cream", price: "10" },
    { name: "Corn Ice Cream", price: "3" },
    { name: "Choco Stick", price: "4" },
    { name: "Avil Milk", price: "8" },
    { name: "Avil Milk Spl", price: "10" },
  ]},
  { id: "bricks", title: "Bricks", items: [
    { name: "Kiwi Bricks", price: "15" },
    { name: "Pineapple Bricks", price: "15" },
    { name: "Mango Bricks", price: "15" },
    { name: "Watermelon Bricks", price: "12" },
    { name: "Mixed Fruit Bricks", price: "18" },
  ]},
  { id: "snacks", title: "Snacks", items: [
    { name: "Egg Puffs", price: "ASP" },
    { name: "Mutta Bhaji", price: "ASP" },
    { name: "Parippu Vada", price: "ASP" },
    { name: "Erachi Pathal", price: "ASP" },
    { name: "Mulak Bhaji", price: "ASP" },
    { name: "Elayada Spicy", price: "ASP" },
    { name: "Elayada Sweet", price: "ASP" },
    { name: "MeenKaayi", price: "ASP" },
    { name: "Meen Pathal", price: "ASP" },
    { name: "Kozhukatta Sweet", price: "ASP" },
    { name: "Sugiyan", price: "ASP" },
    { name: "Neyyappam", price: "ASP" },
    { name: "Kallummakayi", price: "ASP" },
    { name: "Kunji Pathal", price: "ASP" },
    { name: "Pazham Nirachathu", price: "ASP" },
    { name: "Chicken Roll", price: "ASP" },
    { name: "Elangi", price: "ASP" },
    { name: "Uzhunnu Vada", price: "ASP" },
    { name: "Cutlet", price: "ASP" },
    { name: "Pazham Pori", price: "ASP" },
    { name: "Chatti Pathal", price: "ASP" },
    { name: "Chicken Puffs", price: "ASP" },
    { name: "Macroni", price: "ASP" },
    { name: "Unnakayi", price: "ASP" },
  ]},
];

// Export for use in browser or Node environments
if (typeof module !== "undefined" && module.exports) {
  module.exports = { restaurant, categories };
}